### ISSUE TITLE
play all subsongs before going to next song?

### ISSUE THREAD

**Issue by fanoush** [neumatho/NostalgicPlayer#114]
I have some TFMX files with multiple subsongs and the player only plays one subsong and then goes to next one, is there some mode to skip to next subsong instead of next song when current one ends

or maybe in playlist if I could select range of subsongs if it cannot be done in UI - or at least one subsong would be enough in playlist so I can duplicate song in saved playlist with different subsongs

**Comment by neumatho** [comment]
It is not possible at the moment to make the player skip to next sub-song instead of song in the playlist, when a song ends. I will put this on my todo list and probably make it as an option you can set in the settings.

However, in the newest version of NostalgicPlayer, it is possble to select which subsong to start to play when you load the song. That way, you can have the same song several times in the playlist with different sub-songs and by then simulate what you want.

To do this, start playing the song and subsong you want to remember. Then list on the "list" icon below the playlist.

![image](https://github.com/user-attachments/assets/e07dfa2a-f8e9-4ad3-9feb-bd6476bcbf37)

Note the hashtag after the song name. This indicate that a subsong has been selected for the song.

**Comment by fanoush** [comment]
OK, thanks, it is cumbersome but could work. BTW the hashtag could include number of selected subsong like `#3` so you would know which is which if you have it several times in the playlist with different subsongs.

**Comment by neumatho** [comment]
Good idea. I will write that down too.

**Comment by fanoush** [comment]
Thanks a lot. I just checked and I don't see any build or release with it yet so I will check again later.

**Comment by neumatho** [comment]
I will make a new release very soon. Which artifacts do you mean? Binary files from the build?

**Comment by fanoush** [comment]
> Which artifacts do you mean? Binary files from the build?

yes, the pipeline run could make the result available as a zip file, see e.g. this
https://github.com/fanoush/DAPLink/actions/runs/11269786649
scroll down and there are artifacts. When  I check your build https://github.com/neumatho/NostalgicPlayer/actions/runs/11533995341  I don't see any artifacts.

**Comment by neumatho** [comment]
Thanks for info. I will look at it at some point.

**Comment by neumatho** [comment]
A new release has been published.

**Comment by fanoush** [comment]
Thanks a lot, tested and it works fine! I am using it now instead of XMPlay which have some crackling audio issue with Lemmings mid files, this one works fine and now also plays all subsongs :-)
