### ISSUE TITLE
Aegis Sonix plays wrongly Yessonix.xmus

### ISSUE THREAD

**Issue by kenshigros** [neumatho/NostalgicPlayer#129]
[SONIX.zip](https://github.com/user-attachments/files/17966849/SONIX.zip)
Hi.I love your program and hope it is going to use more player soon.
The problem with this score is the main riff when repeating left a one second of silence between the loops.I checked on other programs it does work correctly (they probably use not IFF-SMUS plugin 

Regards

Alex

**Comment by neumatho** [comment]
Thanks for info,

The one second silence you hear, is because the song begins over and it start with one second silence. As I can see, there is nothing in the specification that have some repeat information. Even the original Sonix 2.0 on the Amiga have the silence when repeating.

Which other programs have you checked on. I would like to test it out. Maybe there is some secret information in the file I don't know about :-)

**Comment by kenshigros** [comment]
Hi.Tested it on BZR2 (blazer) and XMPlayer
And used also the real deal on winUAE (Sonic v2.0 on Amiga 1200 OS3.x

Regards,

Alex

PS:Usually I make video captures of what I find since I am almost on everyone forums or discord (bar,modland,demozoo and AMP)
Envoyé de mon iPhone

Le 1 déc. 2024 à 09:24, Thomas Neumann ***@***.***> a écrit :

﻿

Thanks for info,

The one second silence you hear, is because the song begins over and it start with one second silence. As I can see, there is nothing in the specification that have some repeat information. Even the original Sonix 2.0 on the Amiga have the silence when repeating.

Which other programs have you checked on. I would like to test it out. Maybe there is some secret information in the file I don't know about :-)

**Comment by neumatho** [comment]
I can hear it now. I though you were talking about when the song was looping. It sounds like some ADSR is running too fast. I will look at it.

**Comment by neumatho** [comment]
This has been fixed now. The problem was that the player tries to reuse sample data, if two or more instruments uses the same sample. Instead of only sharing the sample, it shares the whole instrument including envelope, vibrato etc. information, which could be different. That's why it was played incorrectly.

If you want, you can try a developer build with the fix, which can be found here:

https://github.com/neumatho/NostalgicPlayer/actions/runs/12221247780
